packages:
  - packages/*
onlyBuiltDependencies:
  - esbuild
  - msw

catalog:
  "@types/node": ^22.18.11
  eslint: ^9.37.0
  playwright: ^1.56.1
  prettier: ^3.6.2
  stylelint: ^16.25.0
  tslib: ^2.8.1
  typescript: ^5.9.3
