packages:
  - packages/*
onlyBuiltDependencies:
  - esbuild
  - msw

catalog:
  "@types/node": ^22.9.1
  eslint: ^9.22.0
  playwright: ^1.50.1
  prettier: ^3.3.3
  stylelint: ^16.14.1
  tslib: ^2.8.1
  typescript: ^5.6.3
