name: Main
on:
  workflow_dispatch:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    needs: [lint, test]
    uses: ./.github/workflows/release.yml
    permissions:
      id-token: write # Required for OIDC
      contents: write # Required to create the release
      pull-requests: write # Required to create the release PR
