name: Release
on:
  workflow_call:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install project dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run --recursive build

      - name: Create empty user .npmrc file
        run: touch ${HOME}/.npmrc

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true # See https://docs.npmjs.com/generating-provenance-statements#using-third-party-package-publishing-tools
