name: Test
on:
  workflow_call:

jobs:
  unit:
    name: Run unit tests with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node: ['lts/*', 'latest', '20']
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Setup Playwright cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps
        working-directory: packages/utils

      - name: Check
        run: pnpm run test:unit:coverage
        working-directory: packages/utils

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: packages/utils
          token: ${{ secrets.CODECOV_TOKEN }}
