name: Test
on:
  workflow_call:

jobs:
  unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Check
        run: yarn run test:unit
