name: Test
on:
  workflow_call:

jobs:
  unit:
    name: Run unit tests with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node: ["lts/*", "latest", "20"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run --recursive build

      - name: Setup Playwright cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Install Playwright browsers
        run: pnpm run playwright:install --with-deps

      - name: Check
        run: pnpm run --recursive test:unit:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
